version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: npm prestart
      timeout: 300
      runas: root
  ApplicationStart:
    - location: npm start app.js
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: npm stop
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 60
      runas: ec2-user